import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const TENANT_ID="11111111-1111-4111-8111-111111111111";
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const strip=(s:string)=>String(s||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/\s+/g," ").trim();
const norm=(s:string)=>strip(s).toLowerCase().replace(/ё/g,"е").replace(/[^a-zа-я0-9]+/gi," ").trim();
function normUrl(raw:string,base:string){try{const u=new URL(raw,base);["utm_source","utm_medium","utm_campaign","utm_term","utm_content","gclid","yclid"].forEach(k=>u.searchParams.delete(k));u.hash="";return u.toString()}catch{return raw}}
async function sha(s:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function dt(v:any){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
const LOCAL=["конаково","конаковск","конаковского","конаковский","конаковском","завидово","редкино","новозавидовский","новозавидово","селихово","городня","козлово","мокшино","радченко","озерки","решетниково","старое мелково","дмитрова гора"];
const TOPIC=["авар","дтп","пожар","отключ","вода","тепл","электр","газ","дорог","ремонт","транспорт","школ","детск","больниц","поликлиник","администрац","суд","полици","мчс","следствен","спорт","турнир","фестив","концерт","выстав","культур","библиот","волга","иваньковск","вакан","работ","строител","благоустрой","эколог","мусор","погода","шторм","лед","павод"];
function score(title:string,snippet:string,source:any,url:string){const text=norm(title+" "+snippet+" "+url);let s=0;const reasons:string[]=[];const local=LOCAL.filter(k=>text.includes(k));if(local.length){s+=Math.min(65,45+local.length*5);reasons.push("география: "+local.slice(0,3).join(", "))}if(source?.parser_config?.official&&local.length){s+=15;reasons.push("официальный источник")}if(source?.parser_config?.critical_city_source){s+=25;reasons.push("городская инфраструктура")}const topics=TOPIC.filter(k=>text.includes(k));if(topics.length){s+=Math.min(20,topics.length*4);reasons.push("темы: "+topics.slice(0,3).join(", "))}try{if(/конаково/i.test(new URL(url,source.url).hostname))s+=10}catch{}return {score:Math.min(100,s),reasons}}
function rss(xml:string,base:string){const out:any[]=[];for(const b of (xml.match(/<item[\s\S]*?<\/item>/gi)||[]).slice(0,80)){const g=(tag:string)=>{const m=b.match(new RegExp("<"+tag+"(?:\\s[^>]*)?>([\\s\\S]*?)<\\/"+tag+">","i"));return m?strip(m[1].replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1")):""};const title=g("title"),link=g("link");if(title&&link)out.push({title,url:normUrl(link,base),snippet:g("description"),external_id:g("guid")||link,published_at:dt(g("pubDate"))})}return out}
function links(html:string,base:string,cfg:any){const out:any[]=[];const re=/<a\b[^>]*href=["']([^"'#]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<120){const title=strip(m[2]);if(title.length<18||title.length>240)continue;const url=normUrl(m[1],base);if(!/^https?:/i.test(url))continue;if(cfg?.path_hint&&!url.includes(cfg.path_hint)&&!norm(title).includes("конаков"))continue;out.push({title,url,snippet:"",external_id:url,published_at:null})}return out}
function heads(html:string,base:string){const out:any[]=[];const re=/<(?:h1|h2|h3|h4)[^>]*>([\s\S]*?)<\/(?:h1|h2|h3|h4)>/gi;let m;while((m=re.exec(html))&&out.length<80){const title=strip(m[1]);if(title.length>=18&&title.length<=240)out.push({title,url:base,snippet:"",external_id:title,published_at:null})}return out}
async function fetchText(url:string){const c=new AbortController();const to=setTimeout(()=>c.abort(),6000);try{const r=await fetch(url,{signal:c.signal,redirect:"follow",headers:{"user-agent":"Konakovo-Ryadom-NewsBot/1.0","accept":"application/rss+xml, application/xml, text/xml, text/html;q=0.9,*/*;q=0.8"}});if(!r.ok)throw Error("HTTP "+r.status);return await r.text()}finally{clearTimeout(to)}}
async function processSource(source:any,maxItems:number){try{const text=await fetchText(source.url);const items=source.kind==="rss"?rss(text,source.url):(source.kind==="html_headings"?heads(text,source.url):links(text,source.url,source.parser_config||{}));const prepared=await Promise.all(items.slice(0,maxItems).map(async(item:any)=>{const rel=score(item.title,item.snippet||"",source,item.url);if(rel.score<Number(source.min_score||55))return null;const maxAgeDays=Number(source?.parser_config?.max_age_days||14);if(item.published_at){const ageMs=Date.now()-new Date(item.published_at).getTime();if(Number.isFinite(ageMs)&&ageMs>maxAgeDays*86400000)return null;}const article_url=normUrl(item.url,source.url);const normalized_hash=await sha(norm(item.title).slice(0,500)+"|"+article_url);const cleanTitle=strip(item.title).slice(0,300);return {tenant_id:TENANT_ID,source_id:source.id,source_name:source.name,source_url:source.url,article_url,external_id:String(item.external_id||"").slice(0,1000)||null,title:cleanTitle,snippet:strip(item.snippet||"").slice(0,4000)||null,draft_body:"По данным источника «"+source.name+"»: "+cleanTitle+".",source_published_at:item.published_at,relevance_score:rel.score,relevance_reasons:rel.reasons,status:"pending",normalized_hash,updated_at:new Date().toISOString()}}));const rows=prepared.filter(Boolean);let inserted=0;if(rows.length){const {data,error}=await db.from("news_candidates").upsert(rows,{onConflict:"tenant_id,normalized_hash",ignoreDuplicates:true}).select("id");if(error)throw error;inserted=data?.length||0}await db.from("news_sources").update({last_checked_at:new Date().toISOString(),last_success_at:new Date().toISOString(),last_error:null,updated_at:new Date().toISOString()}).eq("id",source.id);return {source:source.name,scanned:items.length,eligible:rows.length,inserted,failed:false}}catch(e:any){const message=String(e?.message||e).slice(0,1000);await db.from("news_sources").update({last_checked_at:new Date().toISOString(),last_error:message,updated_at:new Date().toISOString()}).eq("id",source.id);return {source:source.name,scanned:0,eligible:0,inserted:0,failed:true,error:message}}}
Deno.serve(async(req)=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const {data:secretCfg}=await db.from("app_config").select("value").eq("key","news_cron_secret").maybeSingle();const expected=secretCfg?.value?.value||"";if(!expected||req.headers.get("x-news-cron-secret")!==expected)return json({error:"unauthorized"},401);const {data:autoCfg}=await db.from("app_config").select("value").eq("key","news_autocollect").maybeSingle();if(autoCfg?.value?.enabled===false)return json({ok:true,disabled:true});const {data:sources,error}=await db.from("news_sources").select("*").eq("tenant_id",TENANT_ID).eq("enabled",true).order("priority",{ascending:false});if(error)return json({error:error.message},500);const maxItems=Math.min(80,Number(autoCfg?.value?.max_items_per_run||80));const results=await Promise.all((sources||[]).map((s:any)=>processSource(s,maxItems)));const inserted=results.reduce((n:any,x:any)=>n+x.inserted,0);const scanned=results.reduce((n:any,x:any)=>n+x.scanned,0);const failed=results.filter((x:any)=>x.failed).length;if(inserted>0)await db.from("audit_log").insert({tenant_id:TENANT_ID,actor:"news-collector",action:"news_candidates_collected",entity_type:"news_candidate",entity_id:"batch",metadata:{inserted,scanned,failed}});return json({ok:true,sources:results.length,scanned,inserted,failed,results})});