window.KONAKOVO={
  supabaseUrl:'https://lwzqfmrbwtwfeuuikqsw.supabase.co',
  supabaseKey:'sb_publishable_9pf-lAIf7QECTqqE3CkgMQ_LCwSbsYU',
  api:'https://lwzqfmrbwtwfeuuikqsw.supabase.co/functions/v1/admin-api',
  helpApi:'https://lwzqfmrbwtwfeuuikqsw.supabase.co/functions/v1/help-admin',
  businessApi:'https://lwzqfmrbwtwfeuuikqsw.supabase.co/functions/v1/business-admin',
  auditApi:'https://lwzqfmrbwtwfeuuikqsw.supabase.co/functions/v1/audit-admin',
  contentApi:'https://lwzqfmrbwtwfeuuikqsw.supabase.co/functions/v1/content-admin',
  statsApi:'https://lwzqfmrbwtwfeuuikqsw.supabase.co/functions/v1/stats-admin',
  userApi:'https://lwzqfmrbwtwfeuuikqsw.supabase.co/functions/v1/user-admin',
  communityApi:'https://lwzqfmrbwtwfeuuikqsw.supabase.co/functions/v1/community-admin'
};